### PR TITLE
Correct jeenalee's name

### PR DESCRIPTION
**Pull request by malisas**
This change is [Reviewable](https://reviewable.io/reviews/servo/blog.servo.org/108)

### CODE REVIEW

**Comment by KiChjang** [comment]
That's... rather embarrassing, pretend it never happened :).

**Comment by larsbergstrom** [comment]
@jeenalee I'd like to apologize for this mistake! I unfortunately do these by hand and attempt to double-check them all, but this is not the first time I have messed it up. Auto-generating this data so that it never happens again is on our list (https://github.com/servo/servo/wiki/Student-projects), but for now I will redouble my efforts to avoid doing this again :-(

**Comment by jeenalee** [comment]
@larsbergstrom No worries!!! It's really ok :) I understand that hand curating these projects and names takes effort, and I'm grateful for these posts and the shout-out!

**Comment by malisas** [comment]
Yes, thank you for the mentions!! :)

**Comment by larsbergstrom** [comment]
@jeenalee @malisas Thank you both for all of your hard work! Putting together the posts is the much easier part, but I still seem to mess it up :-)

**Pull request merged**
