### PR TITLE
Write up SW gsoc project

### PR DESCRIPTION
**Pull request by jdm**
cc @Manishearth for other project writeup

@creativcoder any comments? :)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/blog.servo.org/116)

### CODE REVIEW

**Comment by creativcoder** [comment]
Thanks for the write up @jdm :)

Just [updated](https://github.com/creativcoder/gsoc16/commit/651520c1ded3202361889f3bbc46c9ae9461cb6a) some links in my gsoc repo to reflect current state of things.

A suggested addition: The ending lines of this post can also talk about the upcoming GSoC'17 projects (if any) for Servo and we can probably link pages, like https://github.com/servo/servo/wiki/Summer-of-Code-projects so any one likely to participate next year can reference this blog post.

**Comment by jdm** [comment]
It is optimistic of you to believe that we have begun any GSoC 2017 planning ;)

**Comment by Manishearth** [comment]
Added writeup for @izgzhen. Feel free to edit.

**Comment by jdm** [comment]
I'll post this once @izgzhen approves.

**Comment by izgzhen** [comment]
It looks good to me. Thanks!

**Comment by izgzhen** [comment]
I checked the blog and found that the section title looks way much big.

Maybe we can change `# ServiceWorker support` etc. to `## ServiceWorker support` or even smaller one

**Comment by jdm** [comment]
Fixed.

**Pull request merged**
